version: '3.5'

services:
  api01: &api
    # image: distanteagle16/rinhabackend:latest
    build: .
    environment:
      HTTP_PORT: 8080
      DB_HOST: localhost
      REDIS_HOST: localhost
      POOL_SIZE: 30
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
    network_mode: "host"

  api02:
    <<: *api
    environment:
      HTTP_PORT: 8081
      DB_HOST: localhost
      REDIS_HOST: localhost
      POOL_SIZE: 30

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'

  redis:
    image: redis
    hostname: redis
    network_mode: host
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
